-- ============================================================
-- Seed v5 — PERGUNTAS do questionário (guiado por dados)
-- Corre DEPOIS de schema_v4.sql.
-- ============================================================
-- Limpa perguntas antigas para poder recorrer este seed sem duplicar.
delete from questions;

-- Perguntas transversais (shared = true, domain_id = null)
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values (NULL, 'contact_name', 'Como te chamas?', NULL, 'text', null, true, 0, 'Sobre ti', 0, true, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values (NULL, 'contact_email', 'Email', 'Para te enviarmos os resultados.', 'text', null, true, 1, 'Sobre ti', 0, true, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values (NULL, 'contact_phone', 'Telefone (opcional)', NULL, 'text', null, true, 2, 'Sobre ti', 0, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values (NULL, 'promoter_age', 'Que idade tens?', 'Muitos apoios têm limites de idade (ex.: até 35 ou 40 anos).', 'number', null, true, 3, 'Sobre ti', 0, true, NULL, 'birth_year_age');
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values (NULL, 'location_district', 'Em que distrito vives ou tens o projeto?', NULL, 'text', null, true, 0, 'Localização', 1, true, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values (NULL, 'location_municipality', 'E o concelho?', NULL, 'text', null, true, 1, 'Localização', 1, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values (NULL, 'tax_situation_ok', 'Tens a situação fiscal e contributiva regularizada?', 'Sem dívidas às Finanças nem à Segurança Social. É exigido na maioria das candidaturas.', 'yesno', null, true, 0, 'Situação', 2, false, NULL, NULL);

-- AGRICULTURA
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'goal', 'O que queres fazer com a tua terra?', 'Por palavras tuas — instalar-me, modernizar, plantar, etc.', 'textarea', null, false, 0, 'O teu objetivo', 3, true, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'investment_type', 'Que tipo de investimento pensas fazer?', NULL, 'select', '["Instalar-me / arrancar", "Máquinas e equipamento", "Obras / construção", "Plantações", "Energia / solar", "Transformar / vender o produto", "Vários / ainda não sei"]'::jsonb, false, 1, 'O teu objetivo', 3, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'budget_eur', 'Orçamento estimado (€)', NULL, 'number', null, false, 2, 'O teu objetivo', 3, false, 'Ex.: 40000', NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'production_mode', 'Modo de produção', 'Biológico ou integrado pode dar majorações.', 'select', '["Convencional", "Biológico", "Produção integrada", "Não sei"]'::jsonb, false, 3, 'O teu objetivo', 3, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'area_ha', 'Área da propriedade (hectares)', NULL, 'number', null, false, 0, 'A propriedade', 4, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'has_water', 'Tens acesso a água?', NULL, 'yesno', null, false, 1, 'A propriedade', 4, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'crops', 'Culturas (atuais ou previstas)', NULL, 'text', null, false, 2, 'A propriedade', 4, false, 'Ex.: olival, vinha, horta', NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'animals', 'Animais (se aplicável)', NULL, 'text', null, false, 3, 'A propriedade', 4, false, 'Ex.: ovinos, abelhas', NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'buildings', 'Edifícios / construções', NULL, 'text', null, false, 4, 'A propriedade', 4, false, 'Ex.: armazém, ruína', NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'activity_open', 'Tens atividade agrícola aberta nas Finanças?', NULL, 'yesno', null, false, 0, 'Enquadramento', 5, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'has_nifap', 'Tens NIFAP (registo no IFAP)?', NULL, 'yesno', null, false, 1, 'Enquadramento', 5, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'first_install', 'É a tua primeira instalação como responsável de exploração?', 'Conta como primeira se nunca foste responsável por uma exploração agrícola.', 'yesno', null, false, 2, 'Enquadramento', 5, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='agricultura'), 'received_aid_before', 'Já recebeste apoios agrícolas antes (Pedido Único, investimento, prémios)?', 'Ter recebido há mais de 2 anos pode afetar a primeira instalação.', 'yesno', null, false, 3, 'Enquadramento', 5, false, NULL, NULL);

-- HABITACAO
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='habitacao'), 'goal', 'O que procuras?', NULL, 'select', '["Comprar a primeira casa", "Arrendar", "Reabilitar / obras", "Ainda a explorar"]'::jsonb, false, 0, 'O teu objetivo', 3, true, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='habitacao'), 'first_home', 'Vai ser a tua primeira habitação própria e permanente?', 'E não foste proprietário de casa nos últimos 3 anos.', 'yesno', null, false, 1, 'O teu objetivo', 3, true, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='habitacao'), 'property_price_eur', 'Preço previsto do imóvel (€)', 'A isenção total de IMT vai até 330.539€.', 'number', null, false, 2, 'O teu objetivo', 3, false, 'Ex.: 200000', NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='habitacao'), 'owns_home', 'És atualmente proprietário de alguma habitação?', NULL, 'yesno', null, false, 1, 'Situação', 2, false, NULL, NULL);

-- ENERGIA
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='energia'), 'goal', 'O que queres fazer?', NULL, 'select', '["Instalar painéis solares", "Trocar eletrodomésticos a gás por elétricos", "Baterias / armazenamento", "Eficiência energética da casa", "Ainda a explorar"]'::jsonb, false, 0, 'O teu objetivo', 3, true, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='energia'), 'owns_home', 'A casa onde queres instalar é tua?', NULL, 'yesno', null, false, 1, 'O teu objetivo', 3, false, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='energia'), 'budget_eur', 'Quanto pensas investir (€)?', NULL, 'number', null, false, 2, 'O teu objetivo', 3, false, 'Ex.: 5000', NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='energia'), 'buildings', 'Tipo de habitação', NULL, 'text', null, false, 3, 'O teu objetivo', 3, false, 'Ex.: moradia, apartamento', NULL);

-- EMPRESAS
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='empresas'), 'goal', 'Descreve a tua ideia de negócio', NULL, 'textarea', null, false, 0, 'O teu objetivo', 3, true, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='empresas'), 'company_exists', 'A empresa já está constituída?', 'Muitos apoios exigem que a empresa AINDA não exista à data do pedido.', 'yesno', null, false, 1, 'O teu objetivo', 3, true, NULL, NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='empresas'), 'budget_eur', 'Investimento inicial estimado (€)', NULL, 'number', null, false, 2, 'O teu objetivo', 3, false, 'Ex.: 15000', NULL);
insert into questions (domain_id, field, label, hint, input_type, options, shared, sort_order, section, section_order, required, placeholder, also_writes) values ((select id from domains where slug='empresas'), 'investment_type', 'Em que vais usar o apoio?', NULL, 'select', '["Equipamento", "Instalações", "Stock inicial", "Marketing / arranque", "Vários"]'::jsonb, false, 3, 'O teu objetivo', 3, false, NULL, NULL);
